# Generated by Django 6.0.3 on 2026-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_followed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.FloatField(default=16.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_books',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_new_follower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='playback_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reader_theme',
            field=models.CharField(default='Dark', max_length=20),
        ),
    ]
