# Generated by Django 6.0.3 on 2026-04-28 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='verification_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_links',
            field=models.TextField(blank=True, help_text='Social media or portfolio links'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
