# Generated by Django 6.0.3 on 2026-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_is_suspended_profile_suspension_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
