# Generated by Django 6.0.3 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_word_goal',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_writing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
