# Generated by Django 6.0.3 on 2026-04-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_current_streak_profile_daily_word_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
