# Generated by Django 6.0.3 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_notification_action_type_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
