# Generated by Django 6.0.3 on 2026-04-16 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_is_trending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('LIKE', 'New Like'), ('COMMENT', 'New Comment'), ('NEW_BOOK', 'New Book'), ('FOLLOW', 'New Follower'), ('SYSTEM', 'System Message'), ('POST_LIKE', 'New Post Like'), ('POST_COMMENT', 'New Post Comment'), ('REPOST', 'New Repost'), ('POST_COMMENT_LIKE', 'New Post Comment Like')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
