# Generated by Django 6.0.3 on 2026-04-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chapter_audio_file'),
        ('social', '0006_alter_notification_action_type_postcommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.chapter'),
        ),
    ]
