# Generated by Django 6.0.3 on 2026-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('LIKE', 'New Like'), ('COMMENT', 'New Comment'), ('NEW_BOOK', 'New Book'), ('FOLLOW', 'New Follower'), ('SYSTEM', 'System Message'), ('POST_LIKE', 'New Post Like'), ('POST_COMMENT', 'New Post Comment'), ('REPOST', 'New Repost'), ('POST_COMMENT_LIKE', 'New Post Comment Like'), ('DIRECT_MESSAGE', 'Direct Message')], max_length=20),
        ),
    ]
