# Generated by Django 6.0.3 on 2026-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_slug_purchase_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='region',
            field=models.CharField(db_index=True, default='Global', max_length=50),
        ),
    ]
