# Generated by Django 6.0.3 on 2026-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
