# Generated by Django 6.0.3 on 2026-04-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_language_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(db_index=True, default='English', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags e.g. #romance, #fantasy', max_length=255, null=True),
        ),
    ]
