# Generated by Django 6.0.3 on 2026-04-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_book_language_alter_book_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book', 'order')},
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
