# Generated by Django 6.0.3 on 2026-04-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='book_audio/'),
        ),
    ]
