# Generated by Django 6.0.3 on 2026-04-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_chapter_audio_file_book_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_audio/'),
        ),
    ]
