# Generated by Django 6.0.3 on 2026-04-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_chapter_coins_required_chapter_is_premium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bible', to='core.book')),
            ],
        ),
    ]
