# Generated by Django 6.0.3 on 2026-04-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dailywritingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.chapter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
