# Generated by Django 6.0.3 on 2026-04-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chapterversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('source_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.chapter')),
                ('target_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='core.chapter')),
            ],
        ),
    ]
