# Generated by Django 6.0.3 on 2026-04-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chapterchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend', 'Friend'), ('enemy', 'Enemy'), ('family', 'Family'), ('lover', 'Lover'), ('ally', 'Ally'), ('other', 'Other')], default='friend', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('from_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.storycharacter')),
                ('to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.storycharacter')),
            ],
        ),
    ]
