# Generated by Django 6.0.3 on 2026-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at']},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userachievement',
            old_name='earned_at',
            new_name='unlocked_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='badge_icon',
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('consistency', 'Consistency & Grit'), ('words', 'Word Count Milestones'), ('community', 'Community & Sprints'), ('world', 'World-Building'), ('reader', 'Reader Engagement')], default='consistency', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', help_text='Emoji or icon code', max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='criteria_type',
            field=models.CharField(help_text='Internal identifier for evaluation logic', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='threshold',
            field=models.IntegerField(default=1, help_text='Number required to unlock'),
        ),
    ]
