# Generated by Django 6.0.3 on 2026-04-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_book_ai_evaluation_status_book_ai_flag_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('moderation', 'Moderation'), ('support', 'User Support'), ('finance', 'Financial / Payouts'), ('general', 'General')], default='general', max_length=20)),
            ],
        ),
    ]
