# Generated by Django 6.0.3 on 2026-04-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_savedresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_theme', models.CharField(choices=[('default', 'Srishty Classic'), ('halloween', 'Dark Halloween 🎃'), ('winter', 'Festive Winter ❄️'), ('sakura', 'Spring Sakura 🌸'), ('midnight', 'Midnight OLED')], default='default', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('global_announcement', models.TextField(blank=True, null=True)),
                ('author_commission_rate', models.FloatField(default=70.0)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_boosted', '-priority', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_boosted',
            field=models.BooleanField(default=False, help_text='Boosted categories are highlighted on mobile'),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher priority categories appear first'),
        ),
    ]
